// Code generated by sqlc. DO NOT EDIT.
// source: boxes.sql

package db

import (
	"context"
)

const listBoxes = `-- name: ListBoxes :many
SELECT id, name, created_at FROM boxes
`

func (q *Queries) ListBoxes(ctx context.Context) ([]Box, error) {
	rows, err := q.db.QueryContext(ctx, listBoxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Box
	for rows.Next() {
		var i Box
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
