// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBox(ctx context.Context, name string) (Box, error)
	CreateHostname(ctx context.Context, arg CreateHostnameParams) error
	GetBox(ctx context.Context, id uuid.UUID) (Box, error)
	ListBoxes(ctx context.Context) ([]Box, error)
	ListHostnamesByBox(ctx context.Context, boxID uuid.UUID) ([]Hostname, error)
	ListHostnamesByBoxFilter(ctx context.Context, arg ListHostnamesByBoxFilterParams) ([]Hostname, error)
}

var _ Querier = (*Queries)(nil)
